config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "articles#index" # For devise

  get 'home/index'
  get '/terms', to: 'terms#show'
  get '/about', to: 'about#show'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resources :comments, only: :create
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_many :comments, dependent: :delete_all

  validates :title, presence: true
  validates :content, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :email, presence: true
    validates :message, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end 

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :authenticate_user!, :only => [:new, :create]

  def index
    @articles = Article.order 'id DESC'
  end

  def show
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path 
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update   
    @article = Article.find(params[:id])    # запрос в БД записи для Article совпадающей по :id из маршрута
 
    if @article.update(params_article)      # если обновление @article удалось
      redirect_to @article                  # перенаправление после обновления на /article/:id
    else
      render action: 'edit'
    end
  end

  def new
  end

  def create                                # создание новой записи: create и params_article 
    @article = Article.new params_article   # создание в памяти, записи для Article (c разрешением)
    
    if @article.save                        # сохранилось? значит валид-я пройдена, .save сам запускает ее
      redirect_to @article                  # редирект на '/articles' #show
    else                                    
      render action: 'new'                  # иначе вывод экшена 'new' (его вида)
    end                           
  end

  private                                   # все что ниже не доступно из вне

  def params_article                        # метод для явного разрешения передачи параметров
    params.require(:article).permit(:title, :content)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    
    @comment = @article.comments.new(params_comment)
    @comment[:author] = current_user.username
    @comment.save
    
    redirect_to article_path(@article)
  end

  private

  def params_comment # метод для явного разрешения передачи параметров
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    def new
    end
    
    def create
        @contact = Contact.new contact_params
        if @contact.valid?
            @contact.save
        else
            render action: 'new'
        end
    end

    private

    def contact_params
        params.require(:contact).permit(:email, :message)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/about/show.html.erb
<div class="d-flex justify-content-center">
  <div class="spinner-grow" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>

app/views/articles/_create.html.erb
<h1>Well done!</h1>
<p>Article successfully added</p>
<%= link_to 'Show all articles', articles_path %> <!-- не hard coded ссылка -->

app/views/articles/create.html.erb
<h1>Well done!</h1>
<p>Article successfully added</p>
<%= link_to 'Show all articles', articles_path %> <!-- не hard coded ссылка -->

app/views/articles/edit.html.erb
<h1>Edit article
<small><%= link_to 'add new', new_article_path, class: "badge badge-pill badge-success" %></small>
</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>          
  <div class="form-group">                                    
    <%= f.label :title %><br />
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br />
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save article changes", class: "btn btn-primary" %>
  </div>
<% end %>

<p>
 <%= link_to "Back", :back %> 
</p>

app/views/articles/index.html.erb
<h1>List of articles 
  <% if user_signed_in? %>
    <small><%= link_to 'add new', new_article_path, class: "badge badge-pill badge-success" %></small>
  <% end %>
</h1>
 
<% @articles.each do |article| %>
  <br />
  <i class="text-muted">
    created at: <%= article.created_at.strftime("%e %B %Y, %H:%M") %> • 
    updated at: <%= article.updated_at.strftime("%e %B %Y, %H:%M") %> 
  </i>

  <!--Проверка авторзации пользователя, чтобы разрешить edit/delete-->
  <% if user_signed_in? %>
    <span class="text-muted"> — </span>
    <%= link_to 'Edit', edit_article_path(article), class: "badge badge-pill badge-secondary" %>
    <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}, class: "badge badge-pill badge-danger" %>
  <% end %>

  <br />

  <h2 class="display-4"><%= link_to article.title, article_path(article) %></h2>
  <p class="lead"><%= truncate(article.content, length: 400, omission: ' ... '){link_to "Read more", article_path(article)} %></p>
  
  <hr />
<% end %>

app/views/articles/new.html.erb
<h1>Add new article</h1>

<%= form_for :article, url: articles_path do |f| %>

  <% if @article && @article.errors.any? %>
    <div class="alert alert-warning" role="alert">
    <% @article.errors.full_messages.each do |msg| %>
      <ul>
      <li><%= msg %></li>
      </ul>
    <% end %>
    </div>
  <% end %> 
 
  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br />
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <p>
    <%= f.submit "Save article", class: "btn btn-primary" %>
  </p>  
<% end %>

<p>
 <%= link_to "Back", :back %> 
</p>

app/views/articles/show.html.erb
<!--Вывести заголовок статьи-->
<p>
  <h1 class="display-4"><%= @article.title %></h1>
</p>

<p>
<!--Вывести created_at и updated_at, с модификацией формата вывода-->
  <i class="text-muted">
    created at: <%= @article.created_at.strftime("%e %B %Y, %R") %> • 
    updated at: <%= @article.updated_at.strftime("%e %B %Y, %R") %> 
  </i>

<!--Если пользователь вошел под логином/паролем дать возможность редактировать/удалять статью-->
<!--Нужно закрепить каждую статью за своим пользователем, чтобы чужую нельзя было редактировать/удалять-->
  <% if user_signed_in? %>
    <span class="text-muted"> — </span>
    <%= link_to 'Edit', edit_article_path(@article), class: "badge badge-pill badge-secondary" %>
    <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: 'Are you sure?'}, class: "badge badge-pill badge-danger" %>
    <%= link_to 'Add new', new_article_path, class: "badge badge-pill badge-success" %>
  <% end %>
</p>

<!--Вывести текст статьи-->
<p class="lead">
  <%= @article.content %>
</p>

<!--Вывести комменты к статье-->
<% if @article.comments != [] %>
  <br /><h2>Комментарии</h2>
  <p>
    <% @article.comments.each do |comment| %>
      
      <div class="card">
        <div class="card-header">
          <i> <%= comment.author %> says:</i>
        </div>

        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p><%= comment.body %></p>
          </blockquote>
          <footer class="blockquote-footer">
            <i>created at: <%= comment.created_at.strftime("%e %B %Y, %R") %></i>
          </footer>
        </div>
      </div> <!--/.card--> <br />
     <% end %>
  </p>
<% end %>

<!--Если пользователь авторизовался-->
<% if user_signed_in?%>
<!--Отдаем форму размещения коментов-->
<br /><h2>Оставить комментарий</h2>
<p>
  <%= form_for([@article, @article.comments.build]) do |f| %>
    <!--Поле ввода имя автора не актуальна, теперь имя берется из username p>
      <%= f.label :author %>
      <%= f.text_field :author %>
    </p-->
    <div class="form-group">
      <!-- <%= f.label :body %> -->
      <%= f.text_area :body, class: "form-control", placeholder: "Input your comment here"  %>
    </div>
    <p>
      <%= f.submit "Create comment", class: "btn btn-primary" %>
    </p>  
  <% end %>
</p>
<% else %><br />
  <div class="alert alert-warning" role="alert">
    To leave a comment <%= link_to 'Sign in', new_user_session_path, class: "alert-link" %>
    or <%= link_to 'Sign up', new_user_registration_path, class: "alert-link"  %>
  </div>
<% end %>

app/views/contacts/create.html.erb
<h1>Thanks for you message</h1>

app/views/contacts/new.html.erb
<h1>Contact us</h1>

<%= form_for :contact, url: contacts_path do |f| %>

  <% if @contact && @contact.errors.any? %>

    <div class="alert alert-warning" role="alert">
      <% @contact.errors.full_messages.each do |msg| %>
        <ul>
          <li><%= msg %></li>
        </ul> 
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :message %><br />
    <%= f.text_area :message, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit 'Send Message', class: "btn btn-primary" %>
  </div>

<% end %>

<p>
 <%= link_to "Back", :back %> 
</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- bootstrap connect -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- /bootstrap connect -->
  </head>

  <body>
    <div class="container">

      <nav class="navbar navbar-expand-lg navbar-light bg-white shadow p-3 mb-5 rounded">
        <a class="navbar-brand" href="">
        <%= image_tag "lg.png", size: "36x36", class: "d-inline-block align-top" %>
        learn_ror</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'List', articles_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Add', new_article_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Contacts', contacts_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'About', about_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Terms', terms_path, class: "nav-link"%>
            </li>
          </ul>
          <span class="navbar-text">
            <% if user_signed_in? %>
              Hello, <%= link_to current_user.username, edit_user_registration_path %> | 
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to 'Sign in', new_user_session_path %>
            <% end %>
          </span>
        </div> <!-- /.collapse --> 
      </nav>

      <% if notice != nil %>
        <p class="notice alert alert-success"><%= notice %></p>
      <% end %> 
      <% if alert != nil %>
        <p class="alert alert-danger" role="alert"><%= alert %></p>
      <% end %>  

<br />
      <%= yield %>

    </div> <!-- /.container -->  
  </body>
</html>

app/views/terms/show.html.erb
<div class="d-flex justify-content-center text-warning">
  <div class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>